/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testRandomQuote() {
        String currentDir = System.getProperty("user.dir"); //current directory
        currentDir += "/test/resources/recentquotes.json";

        App randomQuote = new App();
        try {

        assertEquals(randomQuote.app(currentDir), "");
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}