/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void testGetRandomQuote() throws IOException {
        Random random = new Random(0);
        App app = new App(random);
        Quote quote = app.getRandomQuote();
        assertNotNull(quote);
        assertTrue(quote.getAuthor().length() > 0);
        assertTrue(quote.getText().length() > 0);
    }

}