/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.nio.file.Files;
import java.nio.file.Path;

import java.io.*;

import java.nio.file.Paths;

import java.util.Random;

public class App {
         Random random = new Random();

    public App(Random random) {
    }

    public static void main(String[] args) throws IOException {

        // Read the quotes from the JSON file
        Path path = Paths.get("./app/src/main/resources/recentquotes.json");
        String json = Files.readString(path);
        Gson gson = new GsonBuilder().create();
        Quote[] quotes = gson.fromJson(json, Quote[].class);

        // Choose a random quote
        Random random = new Random();
        Quote randomQuote = quotes[random.nextInt(quotes.length)];

        // Output the author and text of the random quote
        System.out.println("Author: " + randomQuote.getAuthor());
        System.out.println("Text: " + randomQuote.getText());


    }

    public Quote getRandomQuote() throws IOException {
        // Read the quotes from the JSON file
        Path path = Paths.get("/Users/dashalewis/projects/courses/code-401-java/quotes2/quotes2/app/src/main/resources/recentquotes.json");
        String json = Files.readString(path);
        Gson gson = new GsonBuilder().create();
        Quote[] quotes = gson.fromJson(json, Quote[].class);

        // Choose a random quote
        int index = random.nextInt(quotes.length);
        Quote randomQuote = quotes[index];

        return randomQuote;

    }

}


