/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;

import java.io.*;

import java.nio.file.Paths;

import java.util.Random;

public class App {
         Random random = new Random();

    public App(Random random) {
    }

    public static void main(String[] args) throws IOException
    {
        Gson gson = new Gson();
        try{
            URL quoteURL = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
            HttpURLConnection quoteConnection = (HttpURLConnection) quoteURL.openConnection();

            try{
                quoteConnection.setRequestMethod("GET");
                int quoteStatus = quoteConnection.getResponseCode();
                System.out.println(quoteStatus);

                if(quoteStatus == 200){
                    InputStreamReader quoteStreamReader = new InputStreamReader(quoteConnection.getInputStream());

                    try(BufferedReader quoteBuffReader = new BufferedReader(quoteStreamReader)){
                        String readQuote = quoteBuffReader.readLine();
                        System.out.println(readQuote);

                        Gson gsonReadQuote = new GsonBuilder().create();
                        QuoteAPI quoteAPIGson = gsonReadQuote.fromJson(readQuote, QuoteAPI.class);
                        System.out.println("DATA FROM QUOTE API CLASS: " + quoteAPIGson);
                        Quote quoter = new Quote(quoteAPIGson.quoteAuthor, quoteAPIGson.quoteText);
//                        System.out.println(quoter.toString());

                        //start array logic to add to end of list
                        // int number == quoter
                        // what we need is an array of quotes and it exists in the get random quote method (98-101 to make array)

                        Path pathArray = Paths.get("./app/src/main/resources/recentquotes.json");
                        String jsonArray = Files.readString(pathArray);
                        Gson gsonQuote = new GsonBuilder().create();
                        Quote[] quotes = gsonQuote.fromJson(jsonArray, Quote[].class);

                        Quote[] newQuotes = new Quote[quotes.length +1];
                        for (int i = 0; i < quotes.length; i++){
                            newQuotes[i] = quotes[i];
                        }

                        newQuotes[newQuotes.length - 1] = quoter;

                        File apiQuoteOut = new File("./app/src/main/resources/recentquotes.json");

                        try(FileWriter apiFileWrite = new FileWriter(apiQuoteOut)){
                            gson.toJson(newQuotes, apiFileWrite);
                            System.out.println("WHAT IS WRITTEN TO FILE: "  + readQuote + apiFileWrite);
                        } catch (IOException e){
                            System.out.println("BAD FILE WRITE");
                            e.printStackTrace();
                        }
                    }
                } else {
                    System.out.println("LOOK UP URL STATUS:" + quoteStatus);
                }

            } catch (IOException e){
                System.out.println("BAD URL");
                e.printStackTrace();
            } finally {
                quoteConnection.disconnect();
            }
        } catch(IOException e) {
            // Read the quotes from the JSON file
            Path path = Paths.get("./app/src/main/resources/recentquotes.json");
            String json = Files.readString(path);
            Gson gsonQuote = new GsonBuilder().create();
            Quote[] quotes = gsonQuote.fromJson(json, Quote[].class);

            // Choose a random quote
            Random random = new Random();
            Quote randomQuote = quotes[random.nextInt(quotes.length)];

            // Output the author and text of the random quote
            System.out.println("Author: " + randomQuote.getAuthor());
            System.out.println("Text: " + randomQuote.getText());
            System.out.println("Used Catch Block and Pulled from JSON File");
            e.printStackTrace();
        }

    }

    public Quote getRandomQuote() throws IOException {
        // Read the quotes from the JSON file
        Path path = Paths.get("../app/src/main/resources/recentquotes.json");
        String json = Files.readString(path);
        Gson gson = new GsonBuilder().create();
        Quote[] quotes = gson.fromJson(json, Quote[].class);

        // Choose a random quote
        int index = random.nextInt(quotes.length);
        Quote randomQuote = quotes[index];

        return randomQuote;

    }

}


