/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.nio.file.Files;
import java.nio.file.Path;

import java.io.*;

import java.nio.file.Paths;

import java.util.Random;

public class App {
         Random random = new Random();

    public String getGreeting() {
        return "Hello World!";
    }

    public String app(String manualPath) throws IOException {
        System.out.println(new App().getGreeting());

        // Read the quotes from the JSON file
        manualPath = manualPath != null ? manualPath : "./app/src/main/resources/recentquotes.json";
        Path path = Paths.get(manualPath);
        String json = Files.readString(path);
        Gson gson = new GsonBuilder().create();
        Quote[] quotes = gson.fromJson(json, Quote[].class);

        // Choose a random quote
        Quote randomQuote = quotes[random.nextInt(quotes.length)];

        // Output the author and text of the random quote
        System.out.println("Author: " + randomQuote.getAuthor());
        System.out.println("Text: " + randomQuote.getText());
        return randomQuote.getAuthor();

    }
//    public static Quote getQuote(Quote[] quotes) {
//
//        // Choose a random quote from the array
//        int maxQuote = 10;
//        int index = random.nextInt(maxQuote);
//        return quotes[index];
//    }

}


